// Date: 2014-07-29 21:04:23
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.zpig333.runesofwizardry.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
//[refactor] no need to mess with this, its the model from Techne
public class ModelStaff extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
  
  public ModelStaff()
  {
    textureWidth = 16;
    textureHeight = 32;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, -13F, 0F, 1, 32, 1);
      Shape1.setRotationPoint(0F, 5F, 0F);
      Shape1.setTextureSize(16, 32);
      Shape1.mirror = false;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 10, 3);
      Shape2.addBox(0F, 0F, 0F, 2, 1, 1);
      Shape2.setRotationPoint(1F, -6.5F, 0F);
      Shape2.setTextureSize(16, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, -1.029744F);
      Shape3 = new ModelRenderer(this, 10, 3);
      Shape3.addBox(-2F, 0F, 0F, 2, 1, 1);
      Shape3.setRotationPoint(0F, -6.5F, 0F);
      Shape3.setTextureSize(16, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 1.029744F);
      Shape4 = new ModelRenderer(this, 10, 3);
      Shape4.addBox(0F, 0F, 0F, 2, 1, 1);
      Shape4.setRotationPoint(2F, -10F, 0F);
      Shape4.setTextureSize(16, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 1.012291F);
      Shape5 = new ModelRenderer(this, 10, 3);
      Shape5.addBox(-2F, 0F, 0F, 2, 1, 1);
      Shape5.setRotationPoint(-1F, -10F, 0F);
      Shape5.setTextureSize(16, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, -1.029744F);
  }
  
  @Override
public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  @Override
public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,e);
  }

}
